# render.yaml

services:
  - type: web
    name: mysite
    plan: free
    env: python-3.10.10
    buildCommand: ./build.sh
    startCommand: python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: WEB_CONCURRENCY
        value: "4"
